version: "3.7"
# each service is a running container, can have multiple ones
services:
  # redis image
  redis:
    image: redis
    networks: 
      - webnet
  # postgres image
  db: 
    image: postgres
    networks: 
      - webnet
    # environment variables  
    environment:
      POSTGRES_PASSWORD: barcelona10
      POSTGRES_USER: postgres
      POSTGRES_DB: slack
  web:
    image: slack-clone-server
    # exposed ports
    ports: 
      - "4040:4040"
    # creates a network where our services can interact with each other
    networks: 
      - webnet
    environment:
      DB_HOST: db
      REDIS_HOST: redis
    # override default staring command
    command: ["./wait-for-it.sh", "db:5432", "--", "node", "index.js"]
networks: 
  webnet:

    
